<?php
include 'db.php';
$pid = $_GET['pid'];

$stmt = $pdo->prepare("SELECT p.*, s.name, s.id as sid 
                       FROM payments p 
                       JOIN students s ON p.student_id=s.id 
                       WHERE p.id=?");
$stmt->execute([$pid]);
$receipt = $stmt->fetch(PDO::FETCH_ASSOC);
?>
<!DOCTYPE html>
<html>
<head>
   <title>Receipt #<?= $receipt['id'] ?></title>
   <style>
      body { font-family: Arial; padding:20px; }
      .receipt { border:1px solid #333; padding:20px; width:400px; margin:auto; }
      h2 { text-align:center; }
      .btn-print { margin-top:15px; }
   </style>
</head>
<body>
   <div class="receipt">
      <h2>Payment Receipt</h2>
      <p><b>Receipt ID:</b> <?= $receipt['id'] ?></p>
      <p><b>Student:</b> <?= $receipt['name'] ?> (ID: <?= $receipt['sid'] ?>)</p>
      <p><b>Amount:</b> ₹<?= $receipt['amount'] ?></p>
      <p><b>Date:</b> <?= $receipt['date'] ?></p>
      <p><b>Mode:</b> <?= $receipt['mode'] ?></p>
      <hr>
      <p><i>Generated by College System</i></p>
      <button onclick="window.print()" class="btn-print">Print</button>
   </div>
</body>
</html>
